package com.tsi.tom.crosby.cocktail_webservice;

// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class SeleniumTests {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void addingaCocktail() {
//        driver.get("http://localhost:3000/");
//        driver.manage().window().setSize(new Dimension(2540, 1420));
//        driver.findElement(By.linkText("Equipment")).click();
//        driver.findElement(By.linkText("Ingredients")).click();
//        driver.findElement(By.linkText("Glasses")).click();
//        driver.findElement(By.linkText("Cocktails")).click();
//        driver.findElement(By.cssSelector("#root > div")).click();
//        driver.findElement(By.cssSelector("input:nth-child(1)")).sendKeys("hello");
//        driver.findElement(By.cssSelector("form")).click();
//        driver.findElement(By.cssSelector("input:nth-child(2)")).sendKeys("434");
//        driver.findElement(By.cssSelector(".smallbutton")).click();
//        String result = driver.switchTo().alert().getText();
//        assertEquals("Cocktail added: 1hello + 2434", result);
    }
}